name: Upload to TestFlight (No Fastlane)

on:
  push:
    branches: 
      - cicd

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -scheme SwiftUIDemo

      - name: Decode App Store Connect API key
        run: echo "$APP_STORE_API_KEY_BASE64" | base64 -d -o AuthKey.p8
        env:
          APP_STORE_API_KEY_BASE64: ${{ secrets.APP_STORE_API_KEY_BASE64 }}

      - name: Clean and Archive
        run: |
          xcodebuild clean archive \
            -scheme SwiftUIDemo \
            -configuration Release \
            -archivePath $PWD/build/SwiftUIDemo.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/SwiftUIDemo.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload to TestFlight via altool
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file build/SwiftUIDemo.ipa \
            --apiKey $APP_STORE_KEY_ID \
            --apiIssuer $APP_STORE_ISSUER_ID
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
