name: Upload to TestFlight (No Fastlane)

on:
  push:
    branches: 
      - cicd

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app  # 根據你的需要調整

      - name: Decode API Key
        run: |
          echo "$APP_STORE_API_KEY_BASE64" | base64 -d -o AuthKey.p8
        env:
          APP_STORE_API_KEY_BASE64: ${{ secrets.APP_STORE_API_KEY_BASE64 }}

      - name: Build archive
        run: |
          xcodebuild clean archive \
            -scheme SwiftUIDemo \
            -configuration Release \
            -archivePath $PWD/build/SwiftUIDemo.xcarchive \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/SwiftUIDemo.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file build/SwiftUIDemo.ipa \
            --apiKey $APP_STORE_KEY_ID \
            --apiIssuer $APP_STORE_ISSUER_ID
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
