name: Build and Upload to TestFlight

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Xcode version (optional)
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Archive the app
        run: |
          xcodebuild clean archive \
            -project SwiftUIDemo.xcodeproj \
            -scheme SwiftUIDemo \
            -configuration Release \
            -archivePath ios/build/SwiftUIDemo.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -quiet

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/SwiftUIDemo.xcarchive \
            -exportPath ios/build \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates \
            -quiet

      - name: Write API Key file
        run: echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" > AuthKey.p8

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file ios/build/SwiftUIDemo.ipa \
            --apiKey "${{ secrets.APPSTORE_KEY_ID }}" \
            --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}"

      - name: Clean up
        run: rm -f AuthKey.p8

      - name: Show job status
        if: always()
        run: echo "Job status:${{ job.status }}"
