name: Build and Upload to TestFlight

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: macos-last
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Archive the app
        run: |
          xcodebuild clean archive \
            -workspace ios/SwiftUIDemo.xcworkspace \
            -scheme SwiftUIDemo \
            -configuration Release \
            -archivePath ios/build/SwiftUIDemo.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -quiet \
            CURRENT_PROJECT_VERSION=${{ steps.buildnumber.outputs.build_number }}

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/SwiftUIDemo.xcarchive \
            -exportPath ios/build \
            -exportOptionsPlist ios/ExportOptions.plist \
            -allowProvisioningUpdates \
            -quiet

      - name: Write API Key file
        run: |
          echo "${{ secrets.APPSTORE_PRIVATE_KEY }}" > AuthKey.p8

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file ios/build/SwiftUIDemo.ipa \
            --apiKey ${{ secrets.APPSTORE_KEY_ID }} \
            --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}
        env:
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}

      - name: Clean up API key
        run: rm -f AuthKey.p8

      - name: Show job status
        if: always()
        run: echo "Job status:${{ job.status }}"
