name: Build and Deploy to TestFlight

on:
  push:
    branches:
      - cicd  # 只有 push 到 cicd branch 時才會觸發

jobs:
  build-and-upload:
    runs-on: macos-latest  # 使用 macOS 執行環境（預設支援 Xcode）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取目前 branch 的原始碼

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app  # 切換 Xcode 版本

      - name: Install signing certificate and provisioning profile
        run: |
          echo "$CERTIFICATE_P12_BASE64" | base64 --decode > certificate.p12  # 解碼憑證
          security create-keychain -p "" build.keychain  # 建立 keychain
          security default-keychain -s build.keychain  # 設定為預設 keychain
          security unlock-keychain -p "" build.keychain  # 解鎖 keychain
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign  # 匯入憑證
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain  # 設定權限
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles  # 建立描述檔目錄
          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/QPPTest.mobileprovision  # 解碼並儲存描述檔
        env:
          CERTIFICATE_P12_BASE64: ${{ secrets.CERTIFICATE_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}

      - name: Build archive
        # 使用 Xcode 手動簽章方式打包為 .xcarchive
        run: |
          xcodebuild \
            -project SwiftUIDemo.xcodeproj \
            -scheme SwiftUIDemo \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/SwiftUIDemo.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER=QPPTest \
            DEVELOPMENT_TEAM=R263GJSADL \
            PRODUCT_BUNDLE_IDENTIFIER=com.qpptec.QPP.Test

      # 建立 ExportOptions.plist 並匯出為 .ipa 檔案
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/SwiftUIDemo.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD/build

      - name: Prepare App Store Connect API Key
        run: |
          mkdir -p ~/.private_keys  # 建立金鑰儲存路徑
          echo "$API_PRIVATE_KEY" | base64 --decode > ~/.private_keys/AuthKey_${API_KEY_ID}.p8  # 解碼並儲存金鑰
        env:
          API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}

      # 使用 altool 上傳 .ipa 至 TestFlight
      - name: Upload to TestFlight using altool
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file build/SwiftUIDemo.ipa \
            --apiKey "$API_KEY_ID" \
            --apiIssuer "$API_ISSUER_ID"
        env:
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
