name: Build and Deploy to TestFlight

on:
  push:
    branches:
      - cicd

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Bump build number
        run: |
          buildNumber=$(date +%s)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "SwiftUIDemo/Info.plist"

      - name: Install signing certificate and provisioning profile
        run: |
          echo "$CERTIFICATE_P12_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/QPPTest.mobileprovision
        env:
          CERTIFICATE_P12_BASE64: ${{ secrets.CERTIFICATE_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}

      - name: Build archive
        run: |
          xcodebuild -project SwiftUIDemo.xcodeproj \
                     -scheme SwiftUIDemo \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/SwiftUIDemo.xcarchive \
                     clean archive \
                     CODE_SIGN_STYLE=Manual \
                     PROVISIONING_PROFILE_SPECIFIER=QPPTest \
                     DEVELOPMENT_TEAM=R263GJSADL \
                     PRODUCT_BUNDLE_IDENTIFIER=com.qpptec.QPP.Test

      - name: Export IPA
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.qpptec.QPP.Test</key>
                  <string>QPPTest</string>
              </dict>
              <key>teamID</key>
              <string>R263GJSADL</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/SwiftUIDemo.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD/build

      - name: Prepare App Store Connect API Key
        run: |
          mkdir -p ~/.private_keys
          echo "$API_PRIVATE_KEY" | base64 --decode > ~/.private_keys/AuthKey_${API_KEY_ID}.p8
        env:
          API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}

      - name: Upload to TestFlight using altool
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file build/SwiftUIDemo.ipa \
            --apiKey "$API_KEY_ID" \
            --apiIssuer "$API_ISSUER_ID"
        env:
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
